### ISSUE TITLE
Copy Information to "Quick Design" section when editing investigation

### ISSUE THREAD

**Issue by tmac2470** [tmac2470/SnapLabs-Server#6]
If you select to edit an investigation it is directed to the detailed design page, this is suitable.  
If you then navigate to the Quick Design, none of the investigation is displayed and when you navigate back to the detailed design the information is lost.

Ideally, the investigation information should be available in both the Detailed and Quick design panels and should stay visible until a new submission is made.

**Comment by MushrChun** [comment]
yeah, that makes sense. I will follow this issue

**Comment by MushrChun** [comment]
I have created a new page to handle the editing function
